sudo: required
dist: trusty
language: node_js
node_js:
  - '4.2'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

script: karma start karma.conf.js --single-run