sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"

before_script:
- npm install -g
- npm install
- npm install --save-dev style-loader
- npm install --save-dev css-loader
- ng build --env=prod
